### ISSUE TITLE
rviz crashes 

### ISSUE THREAD

**Issue by ayushais** [OctoMap/octomap_rviz_plugins#21]
I am trying to use the latest version for rviz plugin to visualize the colorized octomaps on ros-indigo. Every time I try to add the OccupancyGrid or any other plugin, rviz crashes. How can this be fixed?

**Comment by ahornung** [comment]
Do you have more information about the crash, e.g. output on the command line or a crash dump?

**Comment by yumq17** [comment]
@ayushais I have met the same issue! Have you solved it yet?

**Comment by wxmerkt** [comment]
@yumq17 can you add more information, i.e.: version of ROS/Ubuntu, version of rviz, version of octomap_rviz_plugins, and what action you are running that leads to a crash?

**Comment by yumq17** [comment]
@wxmerkt Sorry, i download a wrong version of octomap_rviz_plugins. The issue has been fixed. Thanks a lot!
