### ISSUE TITLE
OccupancyGridStamped Rviz plugin crashed

### ISSUE THREAD

**Issue by fredd2409** [OctoMap/octomap_rviz_plugins#25]
Hi, I'm publishing an OcTreeStamped and want to visualize it with RVIZ. However, when I set the topic /octomap for the plugin in RVIZ, RVIZ crashes completely. I've tried it on three different computers with Ubuntu 16.04 and ROS Kinetic. One computer gives "Segmentation fault (core dumped)". The other two only give "process has died [pid 4342, exit code -11...".

Is this a known issue?

**Comment by ahornung** [comment]
I don't think there's a working visualization for OcTreeStamped, and probably there's not a proper check in place to catch that error.

**Comment by fredd2409** [comment]
I see. I assumed that there was because I can choose the plugin OccupancyGridStamped in RViz and also the code is templated to OcTreeStamped. 

So is there are an obvious reason that this wouldn't work with OcTreeStamped? The data structures aren't fundamentally different (actually not at all?), right? 

Via debugging, I've located that the segmentation fault occurs in this line:
`  std::size_t octree_depth = octomap->getTreeDepth();
` 
(Line 492, occupancy_grid_display.cpp)
But the error only occurs with the OcTreeStamped, not with regular OcTree. On the other hand, the getTreeDepth() works fine with OcTreeStamped in other functions. 

Any quick ideas? Otherwise I'll try to find a fix myself.

Thanks anyway for the quick reply!

**Comment by fredd2409** [comment]
I found the problem. It's that octomap_msgs::msgToMap, or more specifically binaryMsgToMap does not handle OcTreeStamped but only OcTree and ColorOcTree and then returns null. Probably the same issue as [here](https://github.com/OctoMap/octomap_msgs/issues/4). It works when OcTreeStamped is added to that function.

**Comment by ploverpang** [comment]
> I found the problem. It's that octomap_msgs::msgToMap, or more specifically binaryMsgToMap does not handle OcTreeStamped but only OcTree and ColorOcTree and then returns null. Probably the same issue as [here](https://github.com/OctoMap/octomap_msgs/issues/4). It works when OcTreeStamped is added to that function.

Does Anyone fix this bug?

**Comment by wxmerkt** [comment]
Apparently it should be fixed, cf. https://github.com/OctoMap/octomap_msgs/commit/2b390b684782dbed0ad244dbf75923522c40a2f2

Did you encounter this issue? And if so, what versions of octomap_rviz_plugins are you running on which platform?
