### ISSUE TITLE
Free-space nodes cannot be rendered

### ISSUE THREAD

**Issue by MatthiasNieuwenhuisen** [OctoMap/octomap_rviz_plugins#27]
Selecting "Free Voxels" as "Voxel Rendering" type in RViz cannot work, because voxel drawing is terminated early for non-occupied voxels:

https://github.com/OctoMap/octomap_rviz_plugins/blob/0a80d0c6ac513836ba543346ba3776b708a0ecc5/src/occupancy_grid_display.cpp#L517

The actual if that selects whether free-space or occupied voxels are rendered is some lines later in the same if:

https://github.com/OctoMap/octomap_rviz_plugins/blob/0a80d0c6ac513836ba543346ba3776b708a0ecc5/src/occupancy_grid_display.cpp#L526

**Comment by ahornung** [comment]
Good catch! So the outer check can be completely removed? Would you mind submitting a PR?

**Comment by MatthiasNieuwenhuisen** [comment]
PR #30 solves this issue.
