### ISSUE TITLE
Melodic release

### ISSUE THREAD

**Issue by roehling** [OctoMap/octomap_rviz_plugins#33]
Are there any plans to release this package for ROS Melodic? AFAICT it builds just fine.

**Comment by ahornung** [comment]
I can have a look at it, but don't have the resources to test myself, so I would rather prefer transferring maintenance. Any takers?
(ping @wjwwood )

**Comment by wjwwood** [comment]
I cannot take over maintenance unfortunately, but you could ask on the "ros release" discourse group:

https://discourse.ros.org/c/release

**Comment by simonschmeisser** [comment]
I have just tested the plugin as build from source on melodic and it works without changes. Given that @roehling also found no issues you could just release it untested.

If necessary I could also take over maintenance but I have no deep interest into this package and would actually need to learn what "doing a release" implies. I would then ask you a favor in return however: could you have a look why this testcase fails and if my PR makes sense: https://github.com/flexible-collision-library/fcl/pull/309 :wink:

**Comment by liaoheqi123** [comment]
hi , how can l install this package in my ubuntu 18.04  ros-melodic  ?

**Comment by wxmerkt** [comment]
I dont have access to https://github.com/ros-gbp/octomap_rviz_plugins-release.git - otherwise happy to make the release.

**Comment by wjwwood** [comment]
@wxmerkt I invited you to the https://github.com/orgs/ros-gbp/teams/octomap team, which would give you access. 👍

**Comment by wxmerkt** [comment]
Thank you @wjwwood. Melodic release made: https://github.com/ros/rosdistro/pull/21741

**Comment by ahornung** [comment]
Great, thanks!

**Comment by mosquitoam** [comment]
> hi , how can l install this package in my ubuntu 18.04 ros-melodic ?

down load the package , put it in your workplace such  as `~/catkin_ws/src` and `catkin_make`

**Comment by wxmerkt** [comment]
The release has been made and will be part of the next sync.
