### ISSUE TITLE
how to add octomap_rviz_plugins  in rviz

### ISSUE THREAD

**Issue by 920888890** [OctoMap/octomap_rviz_plugins#37]
i have downloaded octomap_rviz_plugins from link. mkdir build && cd build cmake .. make sudo make install

Now octomap_rviz_plugins are installed in /usr/local/share.
but i cannot find it in rviz plugins，is there something wrong or forget to do?
if someone can help me,thanks a lot!

**Comment by 920888890** [comment]
i have solved by source setup.bash in build/devel

**Comment by HuaYuXiao** [comment]
Different to author, I install `octomap_rviz_plugins` with `sudo apt install ros-noetic-octomap*`, but somehow I cannot load this plugin in rviz, any hint for me, tahnkU so much!
