### ISSUE TITLE
noetic

### ISSUE THREAD

**Issue by MakerFace** [OctoMap/octomap_rviz_plugins#38]
How does noetic use the plugin?

**Comment by wxmerkt** [comment]
The package has not yet been released as binaries for Noetic, but it should work. Can you confirm whether the plug-in works for you?

**Comment by wxmerkt** [comment]
Release for Noetic is out - https://github.com/ros/rosdistro/pull/28031 - I'll close this issue for now. If you experience issues with running the plug-in on Noetic, please feel free to open a new issue with details.
