### ISSUE TITLE
Release for foxy

### ISSUE THREAD

**Issue by zapfmp** [OctoMap/octomap_rviz_plugins#40]
Hello,

I'd like to ask if (and when) a release for ROS2 Foxy is planned. This plugin is very important for displaying and debugging our results of working with Octomap.

Thanks in advance!

**Comment by wxmerkt** [comment]
Hi @zapfmp,
Have you tried running the plug-in? I reckon it will need updating to account for changes in messaging. Does it work or could you provide a fix to make it work?

Thanks,
Wolfgang

**Comment by mpzapf** [comment]
Since there seems to be no ROS2 version yet, moving from ROS1 to ROS2 is a major step. The plugins will not run as they are. There will be quite a few adjustments to be made, including the messaging and dependencies. Therefore, I wonder if there is already work done on this.

**Comment by wxmerkt** [comment]
Not from my side (I haven't migrated yet to ROS2) - if someone in the community has done the work and would like to merge/maintain we can either have it on a separate branch or in a separate repository

**Comment by wxmerkt** [comment]
A ROS2 version exists for some time (courtesy of @wep21) and has been released. Closing this issue
